version: '3.4'

services:
  bank:
    image: bank
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Bank_666"
      ACCEPT_EULA: "Y"

  