// <auto-generated />
using System;
using Bank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bank.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20190106002606_hash_pin")]
    partial class hash_pin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bank.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Constant");

                    b.Property<DateTime>("Date");

                    b.Property<string>("DestAccount");

                    b.Property<string>("DestBank");

                    b.Property<int>("FromAccount");

                    b.Property<int>("FromBank");

                    b.Property<string>("Message");

                    b.Property<int>("Specific");

                    b.Property<int>("Variable");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Bank.Models.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Account");

                    b.Property<int>("Bank");

                    b.Property<int>("Constant");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Frequency");

                    b.Property<string>("Message");

                    b.Property<int>("Specific");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Variable");

                    b.HasKey("Id");

                    b.ToTable("Standing");
                });

            modelBuilder.Entity("Bank.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Account");

                    b.Property<int>("Bank");

                    b.Property<int>("Constant");

                    b.Property<string>("Message");

                    b.Property<int>("Specific");

                    b.Property<int>("Variable");

                    b.HasKey("Id");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("Bank.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccountNumber");

                    b.Property<string>("Adress");

                    b.Property<int>("BirthNumber");

                    b.Property<long>("CardNumber");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<long>("Money");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Phone");

                    b.Property<byte[]>("Pin")
                        .IsRequired();

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
